### ISSUE TITLE
Announcement block: Order of listing and dates of event items

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/jekyll-legumeinfo#127]
This affects LIS, PB and SB.
**Expectation from the announcement block** as it has been in used in LIS & PB in classic sites(configurable by curator in Drupal block):
-- Events such as meetings, conferences relevant to the community are announced here.
-- The date of the future event is important than the date on which this event was created by the curator
-- The order of listing is chronological based on the future date of occurrence of the event. Example: the next immediate event may be listed first before an event in the a more distant future.

**Current behaviour**:
-- Behaves like a blog post as opposed to event announcements.
-- The date on which the _posts file is created affects the chronological order of listing of the event.
-- This results in a listing of events that is independent of (chronologically mixed) the actual event dates.
-- The announcement page at https://www.legumeinfo.org/announcements/ is also affected listing the events in a mixed chronological(event occurrence) order.  UX is affected because users have to manually sort out when would be the next couple of events or look for the date of past events.
-- Curator cannot configure in which order the events are to be listed.
-- (ADVANTAGE) Future events can be listed to appear in a future date and not necessarily now (like a blog post).
(https://github.com/legumeinfo/jekyll-legumeinfo/tree/main/announcements/_posts)

**DEVELOPERS NEED**
(I think @alancleary)
- Developer(s) want to know how others(LIS, PeanutBase and SoyBase) feel about the use of this piece of utility and its behavior: as in the past classic site like event listings vs. the current Jekyll behavior like blog posts.  
- They will code the 'common theme and layout' according to inputs and opinions, and need. 
- Should they create another utility called Events?

**Comment by alancleary** [comment]
Once there's consensus from the stakeholders, I can change this in the theme and update the starter site. Someone will need to port it to LIS, though, since it has been severed from the theme. I probably won't be able to get to it until the week of January 16th.

**Comment by sdash-github** [comment]
If the need of the individual Jekyll sites differ (I don't know if it should!), then some provision should be made to list them in the required order (for example in the index.html file) taking the dates from the individually posted files (the .md file within _posts/).  Currently it is: 
`{% for post in site.categories.announcements %}`  # I am interpreting(not sure if this is correct) this is the order in the dir listing.

**Comment by sdash-github** [comment]
Per discussion in LIS-PB meeting, Jan-04:
The events should appear in order of occurrence date, immediate events at top and later events below.  The theme code will need change and @alancleary will attempt the needed modifications when convenient.

PeanutBase will use the changes (@svengato) once this is achieved at LIS.
https://github.com/PeanutBase/jekyll-peanutbase/issues/16

**Comment by alancleary** [comment]
@sdash-github I'm going to try and take care of this today. This is what I plan to implement:

* Change the name of "Announcements" to "Events". The existing "News" item should be used for announcements moving forward.
* Add an optional `end_data` variable to the event front matter that allows events to occur over multiple days, e.g. a conference
* Change the event ordering so that they are shown in chronological order, i.e. events that are currently happening will be first followed by the next upcoming event after that, and so on. Events that have already occurred will be shown in a separate "past events" section on the events page and omitted from the events widget on the main page.
* Adding a date to the filename and in the front matter have the same effect (I'm not sure what happens when you use both...). I'll document that the preferred method is to add the date in the front matter so if there's an end date it'll be in the same place as the (start) date.

 Let me know if I missed anything or if there's any errors.

**Comment by sdash-github** [comment]
I think that should do the job. Thanks.

**Comment by alancleary** [comment]
Commit legumeinfo/jekyll-theme-legumeinfo@69e8ab0e1160ff9fed0d6eee29e918590cbab8f3 in the events branch repurposed (i.e. renamed) the announcements content for events. Announcements should now be made using the news content. New event-specific ordering and display pages still need to be implemented.

**Comment by alancleary** [comment]
Commit legumeinfo/jekyll-theme-legumeinfo@188838b1996eaa0efea7de5488e3deec2cdc4bd4 added code that correctly orders the events and keeps their lists up to date using JavaScript so the site doesn't have to be rebuilt for the upcoming and past events lists to be correct.

**Comment by adf-ncgr** [comment]
done
