### ISSUE TITLE
Issues found testing the Gene Search tool

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#134]
Please report issues that you've found testing the Gene Search tool under this issue. The tool you're reporting on is here:

https://jekyll-dev.lis.ncgr.org/tools/search/gene-search.html

**Comment by sdash-github** [comment]
Test with Arachis gene search (SDash):
1. (Improvement) **Need a count of results**. Total and which counts in current page display: Like "Displaying 1 - 10 of 39 genes" and somewhere  "1 2 3 4 next › last »" in legacy Tripal search result currently available at [Drupal PB](https://peanutbase.org/search/gene) if you want to use it as a guide.
2. Can't find id arahy.2SN1MA when search set to Ara, hy, any (gen, sp, str); Id copied from Drupal gene search at PB. Perhaps a gnm1 feature not in searchable contents.
3. Successful with Arahy.H916D0 (gnm2.ann1 feature).
4. **Linkout non-standard behaviour(!?)**:  Arahy.H916D0 search results gives a normal looking link with options on right-click; but open in new tab takes to the same search result page while my expectation is that it should show details of that gene.  But a standard left click gives the expected linkout options and expected behaviour, takes to mines gene report page. The links in the linkout popup behave like normal links. 

May test more later.

**Comment by StevenCannon-USDA** [comment]
**Sub-issue: Species "any" result is unexpected**

A search with Genus selected returns results only for the first available species, rather than for all species in the genus. Examples:
```
Genus: Phaseolus [SEARCH] --> genes for phaac
Genus: Glycine && Descr: proteasome alpha subunit [SEARCH] --> genes for glycy
```
Expected/preferred:  "any" species returns results for "all" species. This behavior is in effect if Genus and Species are selected but Strain is not; in that case, results are reported for all strains.

**Comment by StevenCannon-USDA** [comment]
**Sub-issue: Drop-down filters aren't retained for "Open link in new tab"**
Setting filters for a search and then doing control-click on a gene link and selecting "open link in a new tab" opens a new search+results window, with results corresponding with an unfiltered search (except filters are retained for Identifier and Description). Example:
```
Genus: Cicer
Description: Proteasome alpha subunit
[SEARCH]
"Open link in new tab" from [cicar.CDCFrontier.gnm1.ann1.Ca_10796]
First result is [aesev.CIAT22838.gnm1.ann1.Ae07g07470] (which is the first Proteasome alpha subunit for -- any -- genus.
```

**Comment by adf-ncgr** [comment]
> **Sub-issue: Species "any" result is unexpected**

@StevenCannon-USDA I think you are just seeing the first page of results, likely phaac come first because of alphabetical precedence; I had to jump forward ~5500 pages (using the URL param, not clicking!) but eventually got to phalu genes. Similarly the glycy genes were at the top of the first page, but scrolling down I think you'll see other species come through alphabetically (glydo, glyd3, etc)

**Comment by sammyjava** [comment]
> 2\. Can't find id arahy.2SN1MA when search set to Ara, hy, any (gen, sp, str); Id copied from Drupal gene search at PB. Perhaps a gnm1 feature not in searchable contents.

That is arahy.Tifrunner.gnm2.ann1.**2SN1MA** / **2SN1MA** in LegumeMine. We've had some confusion on Arachis identifiers and names, partly due to me. The next LegumeMine build will have @StevenCannon-USDA 's updated Arachis naming and should be consistent. It may not match PeanutBase, though, if that's not loaded from the latest LIS Datastore. You'll find that gene if you only put in **2SN1MA**, but the "arahy." in front makes it non-matching. Sorry about that.

**Comment by StevenCannon-USDA** [comment]
@adf-ncgr re "Sub-issue: Species "any" result is unexpected"
Ah, right.  I think I got confused because only one page is indicated "Page 1" -- though there is a "next" page button. So, I guess the enhancement would be: calculate and report the maximum page, in addition to the current page number. Not a high priority, I would say.

Tangentially -- @sammyjava -- do you want to break out any of these sub-issues into their own discrete GH issues (maybe tagged/labeled somehow)?

**Comment by adf-ncgr** [comment]
> **Sub-issue: Drop-down filters aren't retained for "Open link in new tab"**

I think this is the same as point 6 in @sdash-github list. I think the unexpected behavior on open in new tab is due to the fact that this is not a normal link, it is just triggering a javascript action on the same page. Not sure what the best way to prevent people from getting confused by this would be but we should give it some thought since you both stumbled here.

**Comment by sdash-github** [comment]
> 

Found out in my later tests and have modified my comments accordingly.

**Comment by svengato** [comment]
I have been experimenting with updating the gene search tool on the PeanutBase Jekyll site. It works fine, besides the ongoing pagination issues.

1. I need to add hyperlinks around any GO and IPR matches in the **description** field, so that should be wrapped in `unsafeHTML()`. (line 500 of `web-components/src/lis-gene-search-element.ts` - watch for a pull request to this effect)
2. (in the same file) I do not like having the **description** field in italics, but that is easy to change locally if everyone else prefers italics.

**Comment by adf-ncgr** [comment]
@sdash-github review and close or let us know what remains
