### ISSUE TITLE
News block update: Suppress obsolete news items

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/jekyll-legumeinfo#164]
ICLGG 2024 was added yesterday but there are two news items from 2023 that need to be suppressed.

**Comment by sdash-github** [comment]
Found all I need to do is add end date and go through  the site update process.

**Comment by sdash-github** [comment]
Need help:
-- Did the modifications in main (at the github website) in the two files under news and committed. 
-- Was unmindful that it should have been done after creating a branch and then a pull request, merge, tag, etc.
-- Now don't know what to do next from the main branch at the github website.

**Comment by adf-ncgr** [comment]
I think the main thing to get it into production is the tag, so probably just go ahead and do that- I'm not too worried about bypassing stage for this. Or you could just tweak those dates again on a new branch and go through the whole PR/merge process. Maybe there's a more elegant github approach to effect the latter but I think that would at least work.

**Comment by sdash-github** [comment]
Failed to update the release.
Did this:
From https://github.com/legumeinfo/jekyll-legumeinfo clicked tags icon to go to https://github.com/legumeinfo/jekyll-legumeinfo/tags.

Here there is no opportunity to create a new tag. So, clicked Releases, this took me to https://github.com/legumeinfo/jekyll-legumeinfo/releases. Here there is nothing obvious or intuitive to do anything. So,  chose edit icon. Took me to https://github.com/legumeinfo/jekyll-legumeinfo/releases/edit/2024-02-22.1. 
Again I had nothing to edit here from what is there in the various input/choice boxes here; so clicked 'Update release' thinking it will incorporate my changes to the two news files in the updated version. Hard refreshing the prodxn site changed nothing. The two announced events are still there.

**Comment by nathanweeks** [comment]
AFAIK the GitHub web UI doesn't have an interface to create a tag only (independent of a release). It looks like the release edit icon allows the release notes to be edited, but doesn't cause a new tag to be created.

In order to update the production site through the GitHub web UI, a new Release can be created, which would cause a tag to be pushed & trigger the site to build:

https://github.com/legumeinfo/jekyll-legumeinfo/blob/fbf1413cc3a887cf531aed540a273ad17366c72c/.github/workflows/build-deploy.yml#L1-L3

and deployed to production:

https://github.com/legumeinfo/jekyll-legumeinfo/blob/fbf1413cc3a887cf531aed540a273ad17366c72c/.github/workflows/build-deploy.yml#L40-L43

**Comment by adf-ncgr** [comment]
@sdash-github I think this isn't working because end_date only controls visibility of "events" and these meetings were posted as "news". AFAICT "news" items have no provision for being suppressed in the same way that "events" do. @alancleary correct me if I'm wrong. As to why LIS doesn't seem to be using "events" yet, I would assume this is something that relates to not being previously on the theme, but I don't know for sure. In any case, I think we can revisit it but didn't want you to keep banging your head against this...

**Comment by alancleary** [comment]
@adf-ncgr You are correct; `end_date` only works on events. Sorry I didn't catch this yesterday!

**Comment by sdash-github** [comment]
Suspending my activity on this issue until we introduce events at LIS.

**Comment by adf-ncgr** [comment]
@alancleary will add the events block and @sdash-github will manage the content (ie move relevant news items to events)

**Comment by alancleary** [comment]
@sdash-github I enabled events in the `theme-updates` branch. Please move the necessary news items to the new `events/` directory in that branch. Note, you'll have to create a `events/_posts/` directory before moving the news items. I would do it for you but git doesn't supporting adding empty directories to a repo.

**Comment by adf-ncgr** [comment]
this was completed and is now deployed to production
