### ISSUE TITLE
Layout isn't "responsive" (i.e. to smaller windows, mobile, etc.)

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-legumeinfo#49]
Alan sez:

This reminds me, Andrew pointed out that the menu breaks on smaller screens, i.e. the menu simply disappears, which may be part of what motivated Steven to move the links down. This will need to be addressed no matter what navbar we decide to use. Specifically, we'll need to use the UIkit responsive visibility classes to decide at what point the full-size menu is replaced with another, more compact menu (such as one that slides in from off-screen), and then we'll need to program the more compact menu.

Check out the NCGR website's navbar for an example of this in action.

**Comment by sammyjava** [comment]
I think it makes sense to do this in jekyll-theme-legumeinfo (or whatever it becomes called) for starters, since then I'll just copy over the new code. I guess you'll need to fire up a jekyll-legumeinfo-starter repo which uses the theme, which would be a checkout of the abed835bc4376114efa4c7ab1988abaca8c05165 commit in the main branch.

**Comment by sammyjava** [comment]
OK I did it, because I wanted to learn how to attach a submodule:

https://github.com/legumeinfo/jekyll-starter-legumeinfo

This is the golden oldie site before I started mucking with it, so it should be a useful site to use to edit the theme, which is a submodule as before.

**Comment by sammyjava** [comment]
Oh, sorry, @alancleary , I forgot that I'd created this new theme-enabled "starter" site, so please update the theme, I think it is a good update for the theme in general. Or, you can clone a new branch of jekyll-legumeinfo if you'd rather do it there. Thanks!

https://github.com/legumeinfo/jekyll-starter-legumeinfo

That works and has populated dropdowns and uses the _themes/jekyll-theme-legumeinfo/ submodule.

**Comment by alancleary** [comment]
The legumeinfo theme was updated in commit legumeinfo/jekyll-theme-legumeinfo@7eaf1127282b72974b7238debd0be1a48592bd38.

The legumeinfo starter site was updated to use these changes in commit legumeinfo/jekyll-starter-legumeinfo@ccd0eda5c6fc5f7c6a97aba7ce4535461d28cb2a.

@sammyjava @cann0010 Feel free to request revisions  to any of the changes. Otherwise I'll close this issue. Also, note that the `navbar-menu-items.html` file has been renamed `navbar-menu.html` to reflect breaking changes in what this file is supposed to contain. See the [theme's README](https://github.com/legumeinfo/jekyll-theme-legumeinfo#readme) for documentation of how to use the new features.

**Comment by sammyjava** [comment]
Works for me! Thanks! @cann0010 and @adf-ncgr and @nathanweeks take a look at

http://dev.lis.ncgr.org:50030/

which is the shokin branch of this repo, now using Alan's "responsive" update. It seems to do all the things it's supposed to do: horizontal nav when wide; two-row nav when narrower; hamburger menu when really narrow, like a phone.

**Comment by alancleary** [comment]
Thanks, Sam.

I want to emphasize that entire menus (instead of just menu items) are now added via the include files so you can have control over the responsive widths, i.e. you need to pick the width that's appropriate for your specific menu. The responsive widths in the "starter" site are tailored for that specific menu, which I think is the same as LIS. Soybase, however, will likely need to use different widths.

**Comment by adf-ncgr** [comment]
looks great to me- I especially like the way you used plant-based proteins in the "hamburger" menu... thanks for knocking this out, can't wait to see the kids surfing legumeinfo on their phones!

**Comment by alancleary** [comment]
>  take a look at
>
> http://dev.lis.ncgr.org:50030/

@sammyjava It looks like you didn't copy some custom CSS that was added to the header: https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/_includes/head.html#L20

I'll integrate that into the compiled CSS when everyone is happy with how things are.

**Comment by sammyjava** [comment]
Gotcha, done.

**Comment by alancleary** [comment]
>  take a look at
>
> http://dev.lis.ncgr.org:50030/

Clicking on Taxa or Tools in the side-bar opens their sub-menus instead of taking you to their "view all" pages, like in the navbar menus. Some sort of "view all" option should probably be added to these sub-menus (clearly I forgot to do this in the starter site).

**Comment by sammyjava** [comment]
And I'd forgotten to update off-screen-menu and navbar-lower-menu. But since you have to click on Taxa to expand the sub-menu in the off-screen-menu, I don't think it makes sense to have it go to the "view all" page. I think it's good as is.

**Comment by alancleary** [comment]
> But since you have to click on Taxa to expand the sub-menu in the off-screen-menu, I don't think it makes sense to have it go to the "view all" page.

That's not what I was suggesting. I was saying a link to a "view all" page should be added to the <ins>sub-menu</ins> that opens when you click on the Taxa and Tools items in the side-bar. Otherwise there's no way to reach those pages when viewing the site on a small screen.

**Comment by sammyjava** [comment]
Ah, right, sorry. Done.
