### ISSUE TITLE
limit use of target="_blank" to opening new windows only for links going to non *.legumeinfo.org URLs

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#64]
per discussion begun in legumeinfo/jekyll-theme-legumeinfo#15

**Comment by svengato** [comment]
For normal links I am fine with it either way, but perhaps linkouts to legumeinfo.org pages should also keep the target="_blank"?

**Comment by sammyjava** [comment]
The reason I launch links in new tabs is exactly *because* the webapps on other hosts do not necessarily have any return link. You'd replace the LIS site with a new site and you have to use your back arrow, which is no good if you're 15 clicks downstream on the new app, which you're likely to be if you're actually using it.

So, yes, if we *enforce having a clear, consistent link to the main LIS site on EVERY tool*, we don't need to launch in new windows. But until we do that, we should launch in new windows so we don't strand the user on a dead end road. I have no control over the tools so I can't enforce that requirement. The tools were never specified as part of a larger, consistent framework.

We can write a tool spec that says what they need to have in order to be included on the LIS site, and only list tools that satisfy that requirement. One requirement will be a clear, consistent, link back to the main LIS site. Maybe there are others, as well. I'm happy to write that spec if folks are on board with it, and accept that some tools will have to be updated to meet the spec and be listed.

**Comment by sdash-github** [comment]
What happens in a scenario like below?

You are in legumeinfo.org/x/y/z main site at a specific page (x/y/z) and 
from there clicked a link to go to a Tool (opened in same tab, no 
"_blank)" and worked deeper by a few clicks.  In the Tool you have the 
return link to legumeinfo.org but you want to be back to 
legumeinfo.org/x/y/z.  So you have to remember exactly where you were in 
the main site and how did you reach there before going to the Tool.

For this the link to the Tool should use "_blank" like Sam explained 
below or you have to remember to open the Tool in a new tab. This 
happens to me frequently within LIS and in many other sites too.

Just giving a scenario in case you want to consider various possibilities.

Sudhansu

**Comment by adf-ncgr** [comment]
I personally feel like these scenarios are why Browsers created back buttons and similar mechanisms for history traversal; going back 15 clicks if you really need to isn't actually all that hard since (at least in my browser) you can just click-hold the back arrow to get the "history stack" to display. To me the "dead ends" come precisely when there are no page-historical relations, as happens when a page is opened in a new window; I almost always prefer to choose myself when this happens (cmd-click or shift-click), because keeping track of which window spawned which and using the window manager to perform the equivalent of "going back" is hard (for a guy with dozens of windows open, anyway). 

But @sammyjava makes a good point that making some simple tool specifications would go a long way to make disparate tools feel like they are part of the same basic enterprise, and I'd be happy to see him tackle writing such a thing (especially if he will really be happy to do it as he says!).

**Comment by alancleary** [comment]
As far as stuff actually integrated into the Jekyll pages is concerned, you could add a linter via GitHub action that makes all links conform to whatever you decide to do, e.g. it could make sure all off-site link use `target="_blank"` and strip it from any on-site links.

2 cents.

**Comment by sammyjava** [comment]
We're grown up enough to adhere to standards without a linter action.

I'll propose a standard for tools links and how those tools present links back to the main LIS site. In the meantime, let's just leave things as they are. I'll mock up a sample compliant tool header with my re-skinning of the mine sequenceserver.

**Comment by sdash-github** [comment]
Just occurred to me that if a user visits the tool site from soybase or 
peanutbase the link back to LIS is less meaningful. Any thoughts? I 
understand we cannot provide links for every possible needs of an user 
but want to hear how people think about this.

Sudhansu

**Comment by sammyjava** [comment]
My assumption is that all "LIS" tools are under the legumeinfo.org umbrella and hosted on legumeinfo.org subdomains -- meaning that if you link them from another place like PB or SB you accept that you're linking to a completely different web environment just as with a link to NCBI or EMBL. This is made clear by PB being on peanutbase.org and SB being on soybase.org.

**Comment by sdash-github** [comment]
Then that should mean links from PB to these LIS based tools (anything 
with xxx.legumeinfo.org) should be with "_blank", treated as an external 
site.

Sudhansu

**Comment by sammyjava** [comment]
I'm going to close this issue, since the "resolution" is that I'll write a spec for tools saying how they should be linked from the main site and what navigation should be on their headers. I'll make that a new issue.
