### ISSUE TITLE
home page: right hand column of content (news, announcements, blog) gets cut off without horizontal scroll

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-legumeinfo#67]
It seems the main body content is sort of responsive to window resizing, in the sense that the right hand column completely disappears when the window is made horizontally small enough, but it seems not to fit properly and get truncated at what are normal widths on my 13" laptop display. See screenshot below. I'm not personally a big fan of the content just not being available and would prefer a horizontal scroll to indicate that I'm missing out. But maybe that's considered bad design these days; in any case whatever we deem is most appropriate behavior in this regard, it seems awkward to have a partial display. I'll note that on my phone I don't see either the tools sidebar or the news sidebar, and although I can get to tools page via the menu, there is no menu item for News/Announcements. 

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/2009605/156896993-093fa03a-2d20-4447-b2f0-03e3b588aee0.png">

**Comment by sammyjava** [comment]
> I'll note that on my phone I don't see either the tools sidebar or the news sidebar, and although I can get to tools page via the menu, there is no menu item for News/Announcements.

The narrow=phone mode uses the so-called "off-screen" menu, and contains only the main content and the hamburger menu, the idea being it's a phone with just a single content screen as with most phone apps. So that's correct behavior. Good eye on News and Announcements being missing from the hamburger menu, I just fixed that issue (which is entirely separate from the other issue in this issue.)

**Comment by alancleary** [comment]
Digging into this today. Stand by...

**Comment by alancleary** [comment]
OK. I finally got this done in commit legumeinfo/jekyll-theme-legumeinfo@c745dbd34035060de23338e96e47541f8f408c3a.

A few things worth noting:

- This fixes the bug where the right sidebar content was getting clipped by the right side of the screen. It also updates the right sidebar so its content now scrolls with the page since the addition of the blog and its previous non-scrolling behavior was causing it to get clipped by the bottom of the screen as well.
- The right sidebar still disappears when the screen is small enough. I don't make it reappear anywhere else when this happens because that should be an implementation detail of the site (not the theme). Personally I would add "news" and "announcements" links to the navbars since this sidebar only appears on the homepage anyway. Maybe consider putting them under a "community" dropdown if you're worried about space.
- I introduced a new layout called "base" (`_layouts/base.html`) which is now the layout that all other layouts are built on. The "default" layout (`_layouts/default.html`) still exists and will be used when a layout isn't specified, but "base" can be used if you need a page that doesn't have any padding or alignment applied to the content below the navbar, e.g. if you wanted to embed a JBrowse and use as much space as possible.
- I added a little inline JavaScript to the left tools sidebar to fix a clipping bug similar to what this issue reports; specifically, when the navbar got taller because its menu got pushed below the brand, the navbar would cover the top of left tools sidebar. I tried fixing this with vanilla UIkit but couldn't find a solution so I opted for the little bit of inline code.
- Lastly, I added a comment in `_layouts/default.html` pointing out that if you put anything between the tools menu block and the main block, i.e. where the comment is, then the styling will break. This may seem silly but this was actually inherited from the theme we're ripping off and working around it with CSS and/or Jekyll is way messier. So just don't put anything there!

**Comment by sammyjava** [comment]
Closing since @alancleary took care of it.
